### ISSUE TITLE
after clicking full-screen content only resizes if user triggers a tooltip or switches slide

### ISSUE THREAD

**Issue by petervidos** [vizzuhq/vizzu-story-js#31] opened 2023-03-27 21:27 UTC
The contents on the chart should automatically adapt to the size after going in and out of full-screen and not wait for the first interaction.

Currently, it works like this.
![resize_issue](https://user-images.githubusercontent.com/10341970/228070347-ac39b69a-4f0c-49c0-8be7-e147bc86d4d4.gif)

**Comment by simzer** [comment] 2023-08-28 10:01
Duplicate of https://github.com/vizzuhq/vizzu-story-js/issues/44

**Closed by simzer** 2023-08-28 10:01 UTC
